import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { SiLinkedin } from "react-icons/si";
import { DiAndroid } from "react-icons/di";
import { DiJsBadge } from "react-icons/di";
import { FaJava } from "react-icons/fa";
import { FaReact } from "react-icons/fa";
import { SiTailwindcss } from "react-icons/si";
import { AiFillHtml5 } from "react-icons/ai";
import dubpic from "../images/dublin.jpg";
import me from "../images/jorlogo.png";
import pic from "../images/pic.jpg";
import pro from "../images/projectlogo.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-0 ">
        <section className=" min-h-screen  ">
          <nav className="py-2 px-6  bg-black flex justify-between leading-4 ">
          <Image
                    alt=""
                    src={me}
                    className="rounded-full w-32  animate-pulse
                  
                  "
                  ></Image>
           
            
            <ul className="flex items-center gap-8">
              <li className="bg-black">
                <div class="max-w-7xl mx-auto">
                  <div class="relative group">
                    <div class="absolute -inset-1 bg-gradient-to-r from-purple-600 to-pink-600 rounded-lg cursor-pointer blur opacity-25 group-hover:opacity-100 transition duration-1000 group-hover:duration-200"></div>

                    <div class="relative w-23 px-10 py-6 bg-black ring-1 ring-gray-900/5 rounded-lg leading-none flex items-top justify-center space-x-6">
                      <h1 className="text-white group-hover:text-purple-200 transition cursor-pointer duration-300">
                        <a href="https://www.linkedin.com/in/james-jamie-o-reilly-6b9a45207/">

                        
                        LinkedIn
                        </a>
                      </h1>
                    </div>
                  </div>
                </div>
              </li>
              <li className="bg-black">
                <div class="max-w-7xl mx-auto">
                  <div class="relative group">
                    <div class="absolute -inset-1 bg-gradient-to-r from-purple-600 to-pink-600 rounded-lg blur opacity-25 group-hover:opacity-100 transition duration-1000 group-hover:duration-200"></div>
                    <div class="relative w-23 px-10 py-6 bg-black ring-1 cursor-pointer ring-gray-900/5 rounded-lg leading-none flex items-top justify-center space-x-6">
                      <h1 className="text-white group-hover:text-purple-200 transition cursor-pointer duration-300 ">
                      <a href="https://github.com/JayOReilly">
                        GitHub
                        </a>
                      </h1>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </nav>
          {/*---------------------End of Nav Bar---------------------------*/}

          {/*---------------------End Of Portofolio Section---------------------------*/}
          <div
            className="text-center relative 

          
          
          
          bg-black h-screen "
          >
            <div
              className="flex items-center justify-center
            
            
            
            
            bg-black"
            >
              <div
                className=" w-2/3 mt-8 rounded-lg text-white 
               bg-black"
              >
                <div className="flex items-center justify-center mt-4 mb-4 pt-0 flex-col">
                  <Image
                    alt=""
                    src={pic}
                    className="rounded-full w-64 filter saturate-200
                  
                  "
                  ></Image>
                 
                  <h1 className="font-semibold mt-4 text-3xl">A little about me .. </h1>
                  <div className=" grid grid-cols-2 gap-10 items-start">
                  <h1 className="text-2xl  font-semibold text-transparent  text-1xl bg-clip-text  bg-gradient-to-r from-purple-400 to-pink-600  mt-6">
                 <div className=" items-start">
                  ▷ Bsc Computer Science - 2022<br/>
                  ▷ Front End Developer        <br/>
                  ▷ Passion for Design <br/>
                  ▷ Team player<br/>
                  ▷ Always learning <br/>
                  </div>

                  </h1>
                  <h1 className="text-2xl  font-semibold text-transparent  text-1xl bg-clip-text  bg-gradient-to-r from-purple-400 to-pink-600  mt-6">I am 31 years of age and passionate about design, although late to the web development party
                   i intend to make up for lost time and continue to further develop my skills.
                   I have always been a creative type using music production, photography as outlets.
                   Now i intend to let them creative juices express them selves through slick design.</h1>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>

          {/*---------------------End Of Container---------------------------*/}

          {/*---------------------STart of Skills Container---------------------------*/}
          <div className="text-white bg-black flex justify-center text-2xl 
          
          
          
          ">
            <Image src={pro}
            className="object-contain h-72 w-96"
            
            >

            </Image>
            
            
            </div>

          <div class="min-h-screen bg-gradient-to-br  from-black via-black to-black flex flex-col-2 gap-8 justify-center relative overflow-hidden sm:py-10">
            
            
            
            <div class="max-w-7xl mt-0 mx-auto ">
              <div class="relative group">
                <div class="absolute -inset-1 bg-gradient-to-r from-blue-500 to-yellow-600 rounded-lg blur opacity-25 group-hover:opacity-100 transition duration-1000 group-hover:duration-200"></div>
                <div class="relative px-16 py-10 bg-black ring-1 ring-gray-900/5 rounded-lg leading-none flex items-top justify-start space-x-6">
                  <div class="space-y-2">
                    <p class="text-white">Live Weather App - Api Fetch</p>

                    <a
                      href="weatherapi"
                      class="block text-indigo-400 group-hover:text-purple-800 transition duration-200"
                      target="_blank"
                    >
                      Project →
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="max-w-7xl mt-0 mx-auto">
              <div class="relative group">
                <div class="absolute -inset-1 bg-blue-500 rounded-lg blur opacity-25 group-hover:opacity-100 transition duration-1000 group-hover:duration-200"></div>
                <div class="relative px-24 py-10 bg-black ring-1 ring-gray-900/5 rounded-lg leading-none flex items-top justify-start space-x-6">
                  <div class="space-y-2">
                    <p class="text-white">Chat Gpt Integration</p>

                    <a
                      href="https://braydoncoyer.dev/blog/tailwind-gradients-how-to-make-a-glowing-gradient-background"
                      class="block text-indigo-400 group-hover:text-purple-800 transition duration-200"
                      target="_blank"
                    >
                      Project →
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="max-w-7xl mt-0 mx-auto">
              <div class="relative group">
                <div class="absolute -inset-1 bg-blue-500 rounded-lg blur opacity-25 group-hover:opacity-100 transition duration-1000 group-hover:duration-200"></div>
                <div class="relative px-16 py-10 bg-black ring-1 ring-gray-900/5 rounded-lg leading-none flex items-top justify-start space-x-6">
                  <div class="space-y-2">
                    <p class="text-white">4th Year Project - 2022<br/>Android Studio</p>

                    <a
                      href="https://braydoncoyer.dev/blog/tailwind-gradients-how-to-make-a-glowing-gradient-background"
                      class="block text-indigo-400 group-hover:text-purple-800 transition duration-200"
                      target="_blank"
                    >
                      Project →
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/*---------------------Start of Container with Icons---------------------------*/}

          {/*---------------------End of Container with Icons---------------------------*/}

          {/*---------------------Start of Bottom Container ---------------------------*/}

          <div
            className="text-center bg-black h-96 p-20
            text-white mt-0 flex flex-col
          
          "
          >
            <div className="grid grid-cols-2 gap-6 ">
              <div className="flex justify-center m-2 border rounded-lg  text-white">
                <h3 className="text-2xl  px-4">Html</h3>

                <AiFillHtml5 className="text-3xl " />
              </div>

              <div className="flex justify-center m-2 border rounded-lg  text-white">
                <h3 className="text-2xl px-4">JAVA</h3>

                <FaJava className="text-3xl  " />
              </div>

              <div className="flex justify-center m-2 border rounded-lg  text-white">
                <h3 className="text-2xl px-4">Javascript</h3>

                <DiJsBadge className="text-3xl " />
              </div>

              <div className="flex justify-center m-2 border rounded-lg  text-white">
                <h3 className="text-2xl px-4  ">Tailwind CSS</h3>

                <SiTailwindcss className="text-3xl mr-0 " />
              </div>

              <div className="flex justify-center m-2 border rounded-lg  text-white">
                <h3 className="text-2xl px-4  ">React.js</h3>

                <FaReact className="text-3xl mr-0 " />
              </div>
            </div>
          </div>
          {/*---------------------End of Bottom Container ---------------------------*/}

          {/*---------------------Start of Footer---------------------------*/}

          <footer
            class="w-full h-16 bg-black border-t-2 border-white
            abosolute left-0 bottom-0
            flex justify-center items-center
            text-white text-2xl
            "
          >
            Footer Bar
          </footer>
          {/*---------------------End Of Footer---------------------------*/}
        </section>
        {/*---------------------End Of Page---------------------------*/}
      </main>
    </>
  );
}
